name: The Grid Blog
favicon: null
layout_spectrum: 0.10003
typography_spectrum: 0.30664
navigation:
  - url: 'https://thegrid.io/'
    name: Homepage
  - url: 'https://thegrid.ai/thegridsupport/'
    name: Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1c23'
    - '#909792'
    - '#b3b6ad'
    - '#ffffff'
    - '#e6bb4c'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
