name: The Grid Blog
favicon: null
layout_spectrum: 0.17685
typography_spectrum: 0.82679
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/21cc45ca-8033-4a46-950d-6bbd349e93c1.png
style: the-composer
navigation:
  - url: 'https://thegrid.io/'
    name: Home
  - url: 'https://support.thegrid.io/'
    name: Support
  - url: 'http://status.thegrid.io/'
    name: Status
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50607580-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f1f2ed'
    - '#56b0c8'
    - '#354864'
    - '#6e7989'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
