typography_spectrum: 0.82679
color:
  brandColors:
    - '#3bd1dd'
    - '#f99d98'
    - '#fefefe'
    - '#0c7da7'
    - '#0b3f87'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-50607580-7
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/21cc45ca-8033-4a46-950d-6bbd349e93c1.png
name: The Grid Blog
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
navigation:
  - url: 'https://thegrid.io/'
    name: Home
  - url: 'https://support.thegrid.io/'
    name: Support
  - url: 'http://status.thegrid.io/'
    name: Status
favicon: null
purpose: []
