name: The Grid Blog
favicon: null
layout_spectrum: 0.22913
typography_spectrum: 0.30664
navigation:
  - url: 'https://thegrid.io/'
    name: Homepage
  - url: 'https://thegrid.ai/thegridsupport/'
    name: Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f75490'
    - '#203354'
    - '#263455'
    - '#a64879'
    - '#f7548f'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
