layout_spectrum: 0.5470254963172582
typography_spectrum: 0.6110486368716943
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.06043389030344932
  lightness: 0.7319577400445347
  saturation: 0.5712721562997835
  rhythmicContrast: 0.5713368248335537
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/70f0683a-998a-4fb4-b54d-be1bbfc5b7a2.png
  type: null
  appId: null
analytics:
  google: UA-50607580-7
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39c1978d-75dc-4f0e-b06e-b38c6ddc72af.png
name: The Grid Blog
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    url: 'https://thegrid.io/'
    type: external
  - name: Support
    url: 'https://support.thegrid.io/'
    type: external
  - name: Status
    url: 'http://status.thegrid.io/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d55534b3-d050-4829-803d-f52975ed9be2.png
title: The Grid Blog
description: AI Websites
purpose:
  - type: external
    url: 'https://plans.thegrid.io/pro/'
    label: Get on The Grid Now
  - type: external
    url: 'http://help.thegrid.io/category/117-category'
    label: FAQ
github: true
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FaEfpARsP8Fg%3Ffeature%3Doembed%26rel%3D0&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaEfpARsP8Fg&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FaEfpARsP8Fg%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: The Grid
          url: 'https://www.youtube.com/user/TheGridio'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://www.youtube.com/favicon.ico'
        domain: www.youtube.com
      keywords: []
      description: >-
        Meet your new AI web designer. 1. Hire her & get a free domain name. 2.
        Add content & wait a few seconds. 3. Click "redesign" until she crafts
        your website just right. She designed https://thegrid.io/
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/embed/aEfpARsP8Fg?rel=0#11171'
      title: 'The Grid, websites that design themselves'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
