name: The Grid Blog
favicon: null
layout_spectrum: 0.48236
typography_spectrum: 0.30664
navigation:
  - url: 'https://thegrid.io/'
    name: Homepage
  - url: 'https://thegrid.ai/thegridsupport/'
    name: Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f5f7'
    - '#0c0c0c'
    - '#d6d5d3'
    - '#a39f96'
    - '#5e5d59'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
