layout_spectrum: 0.8096432893071324
typography_spectrum: 0.6649284516461194
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.6761081269942224
  lightness: 0.2962971613742411
  saturation: 0.3878569609951228
  rhythmicContrast: 0.9791581698227674
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/70f0683a-998a-4fb4-b54d-be1bbfc5b7a2.png
  type: null
  appId: null
analytics:
  google: UA-50607580-7
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39c1978d-75dc-4f0e-b06e-b38c6ddc72af.png
name: The Grid Blog
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    url: 'https://thegrid.io/'
    type: external
  - name: Support
    url: 'https://support.thegrid.io/'
    type: external
  - name: Status
    url: 'http://status.thegrid.io/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d55534b3-d050-4829-803d-f52975ed9be2.png
title: The Grid Blog
description: AI Websites
purpose:
  - type: external
    url: 'https://plans.thegrid.io/pro/'
    label: Get on The Grid Now
  - type: external
    url: 'http://help.thegrid.io/category/117-category'
    label: FAQ
github: true
