name: The Grid Blog
favicon: null
layout_spectrum: 0.48227
typography_spectrum: 0.21891
navigation:
  - url: 'https://thegrid.io/'
    name: Home
  - url: 'https://support.thegrid.io/'
    name: Support
  - url: 'http://status.thegrid.io/'
    name: Status
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1c23'
    - '#ffffff'
    - '#909792'
    - '#535357'
    - '#deb54b'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
