name: The Grid Blog
favicon: null
layout_spectrum: 0.10003
typography_spectrum: 0.30664
navigation:
  - url: 'https://thegrid.io/'
    name: Homepage
  - url: 'https://thegrid.ai/thegridsupport/'
    name: Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6fffe'
    - '#ffe44d'
    - '#deae63'
    - '#1f1f34'
    - '#6c6c81'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
